export const profileQuestions = [
  { title: "Full Name", key: "fullName", type: "text" },
  { title: "Email Address", key: "emailAddress", type: "email" },
  { title: "Phone Number", key: "phoneNumber", type: "phone" },
  {
    title: "Employment Status",
    key: "employmentStatus",
    type: "dropdown",
    options: ["Employed", "Between Jobs", "Business Owner / Freelancer"],
  },
  {
    title: "Enter Annual Income in AED",
    key: "annualIncome",
    type: "money",
  },
  {
    title: "Emirates ID number",
    key: "emiratesId",
    type: "number",
  },
  { title: "Building name", key: "buildingName", type: "text" },
  { title: "Bedrooms", key: "bedrooms", type: "number" },
  { title: "Location", key: "location", type: "text" },
  { title: "Landlord Name", key: "landlordName", type: "text" },
  {
    title: "Property Type",
    key: "propertyType",
    type: "dropdown",
    options: ["Apartment", "Villa", "Townhouse"],
  },
  { title: "Total Annual Rent", key: "totalAnnualRent", type: "money" },
  {
    title: "Number of Required Cheques",
    key: "numberOfCheques",
    type: "dropdown",
    options: ["1", "2", "3", "4"],
  },
  {
    title: "How much downpayment can you afford?",
    key: "downpayment",
    type: "money",
  },
  {
    title: "Bank",
    key: "selectedBank",
    type: "dropdown",
    options: [
      "Abu Dhabi Commercial Bank",
      "Abu Dhabi Commercial Bank-Islamic",
      "Abu Dhabi Islamic Bank",
      "Ajman Bank",
      "Al Hilal Bank",
      "American Express",
      "Arab Bank",
      "Citibank",
      "Commercial Bank International",
      "Commercial Bank of Dubai",
      "Dubai First",
      "Dubai Islamic Bank",
      "Emirates Islamic",
      "Emirates NBD",
      "Finance House",
      "First Abu Dhabi Bank",
      "HSBC",
      "Liv",
      "MySeva",
      "Najm",
      "National Bank of Fujairah",
      "Noor Bank",
      "Samba",
      "Sharjah Islamic Bank",
      "Standard Chartered Bank",
      "United Arab Bank",
      "simplylife from ADCB",
    ],
  },
];
